
let computerSound = null;

async function playSound(type) {
  const sounds = {
    COMPUTER: 'computerWorking.mp3',
    WARNING: 'computerWarning.mp3',
	ERROR: 'computerError.mp3',
    REPORT: 'computerPrintingScreen.mp3',
    BEEP: 'computerBeep.mp3',
    KEY: 'computerKey.mp3'	
	};

  const audioFile = sounds[type];
  
  if (type === 'COMPUTER') {
    // Se já está tocando, não reinicia
    if (computerSound) return;
    computerSound = new Audio(audioFile);
    computerSound.loop = true;
    computerSound.play();
  } else {
    // Sons únicos
    const sound = new Audio(audioFile);
    sound.play();
  }
}

async function sha256(text) {
        const encoder = new TextEncoder();
        const data = encoder.encode(text);
        const hashBuffer = await crypto.subtle.digest('SHA-256', data);
        const hashArray = Array.from(new Uint8Array(hashBuffer));
        const hashHex = hashArray.map(b => b.toString(16).padStart(2, '0')).join('');
        return hashHex;
    }
	
async function processLogin(logg) {
	    if ( logg.toLowerCase() == "exit" ) {
			login = true;
			senha = false; 
			user = 0;
			hierarquiaMenu = 1;
			output.innerHTML = '';
			window.location.href = 'index.html?cena=1';
			return;
			}
			
		//const logHASH = await sha256(logg.toLowerCase());
		//if (logHASH === "0b2362bfef255c87425771ae1f790d4893a267a869eafe6d6d974ae2c9291d01") {
		if (logg.toLowerCase()=="zanko") {
			writeText(output,"Senha:")
			senha = true; 
			user = 5;
        }
		else
		//if (logHASH === "88e74ca184a121978a0208f7d7bd266fa0bdbeec656419863c400aaba574a1d0") {
		if (logg.toLowerCase()=="guedes") {
			writeText(output,"Senha:")
			senha = true; 
			user = 3;
        }		
		else
		//if (logHASH === "934ca58234d353a03719d55ccbd9f3d4b56f5f61dfbddc957017b0ccc163d3d5") {
		if (logg.toLowerCase()=="arcanjo") {
			writeText(output,"Senha:")
			senha = true; 
			user = 1;
        }		
		else { 
		    writeText(output,"Login inválido.\nLogin:")
			playSound("ERROR");
		}
    }
	
async function processSenha(logg) {
		//const logHASH = await sha256(logg.toLowerCase());
		if ((user == 5) && (logg.toLowerCase() == "vitoria")){ //(logHASH === "a5f3cf1c18f9174d01a6a13f0cc4fbec96f3d26dc1882e217001e36b6511bdc2")) {
			writeText(output,"Validação efetuada com sucesso.\n")
			await wait(250)
			login = false;
			writeText(output, mostrarMenuPrincipal());
        }
		else 
		if ((user == 3) && (logg.toLowerCase() == "chocolate")){//&& (logHASH === "7499aced43869b27f505701e4edc737f0cc346add1240d4ba86fbfa251e0fc35")) {
			writeText(output,"Validação efetuada com sucesso.\n")
			await wait(250)
			login = false;
			writeText(output, mostrarMenuPrincipal());
        }			
		else 
		if ((user == 1) && (logg.toLowerCase() == "arcanjo")){//&& (logHASH === "934ca58234d353a03719d55ccbd9f3d4b56f5f61dfbddc957017b0ccc163d3d5")) {
			writeText(output,"Validação efetuada com sucesso.\n")
			await wait(250)
			login = false;
			writeText(output, mostrarMenuPrincipal());
        }			
		else { 
		    writeText(output,"Senha inválida.\nSenha:")
			playSound("ERROR");
		}
    }

async function processInqueritos(logg) {
	    if ( logg.toLowerCase() === "v" ) {
			consultaInqueritos = false
			output.innerHTML = ''
		    hierarquiaMenu = 1;
			writeText(output, mostrarMenuPrincipal())
			return
		}
	    //const logHASH = await sha256(logg.toLowerCase());
        //if (logHASH === "c15610e73a7a4fe53bbc9b3d74f8e12d58c1f647562d4d772e03177f639004c0") {
		//	texto=decodeURIComponent(escape(atob("			LS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0KPiBJREVOVElGSUNBw4fDg08KLSBJRDogSU5RLTEyNy9BLzY2Ci0gQVNTVU5UTzpHUlVQTyBFU1RVREFOVElMICdGUkVOVEUKTElWUkUnCi0gU1RBVFVTOiBFTSBBTkRBTUVOVE8KLSBDTEFTU0lGSUNBw4fDg086IFJFU1RSSVRPIC0gSU5URVJOTwotIElOw41DSU8gRE8gSU5RVcOJUklUTzogMTIvMDMvMTk2NgotIFJFU1BPTlPDgVZFTDogQUcuIDIzMSDigJMgU0VUT1IgREUKQ09OVFJBSU5URUxJR8OKTkNJQQotLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLQo+IE9CSkVUSVZPCi0gQXB1cmFyIGF0aXZpZGFkZXMgc3VidmVyc2l2YXMsCnJldW5pw7VlcyBjbGFuZGVzdGluYXMgZSBwcm9kdcOnw6NvIGRlCm1hdGVyaWFpcyBkZSBjdW5obyBjb250csOhcmlvIGFvcwppbnRlcmVzc2VzIG5hY2lvbmFpcywgYXRyaWJ1w61kb3MgYW8KZ3J1cG8gZGVub21pbmFkbyAnRlJFTlRFIExJVlJFJy4KLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0KPiBFTlZPTFZJRE9TIElERU5USUZJQ0FET1MKLSBNQVJJQSBIRUxFTkEgRE9TIFNBTlRPUyDigJMgTUFUUklaCklOVEVMRUNUVUFMIOKAkyBWSUdJTMOCTkNJQSBBVElWQQotIFBBVUxPIFJPQkVSVE8gREUgQUxNRUlEQSDigJMgTMONREVSCk9SR0FOSVpBQ0lPTkFMIOKAkyBTT0IgRVNDVVRBCi0gSk9Tw4kgQ0FSTE9TIEZPTlNFQ0Eg4oCTIExPR8ONU1RJQ0EgREUKRVZFTlRPUyDigJMgTU9OSVRPUkFNRU5UTwotIERFTUFJUyBQQVJUSUNJUEFOVEVTIOKAkyBOw4NPCklERU5USUZJQ0FET1MgKE9CU0VSVkHDh8ODTyBDT05Uw41OVUEpCi0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tCj4gQVRJVklEQURFUyBSRUdJU1RSQURBUwotIDE1LzAzLzE5NjYg4oCTIFJFVU5Jw4NPIE5BIEZBQ1VMREFERSBERQpMRVRSQVMg4oCTIDEyIFBBUlRJQ0lQQU5URVMKLSAyOC8wMy8xOTY2IOKAkyBESVNUUklCVUnDh8ODTyBERQpQQU5GTEVUT1MgQ09OVFJBIE8gUkVHSU1FCi0gMDIvMDQvMTk2NiDigJMgVEVOVEFUSVZBIERFIE9SR0FOSVpBUgpBVE8gUMOaQkxJQ08gKEZSVVNUUkFETykKLSAwOS8wNC8xOTY2IOKAkyBERVRFQ8OHw4NPIERFIENPTVVOSUNBw4fDg08KQ09NIElORElWw41EVU8gTk8gRVhURVJJT1IKLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0KPiBBTsOBTElTRSBERSBSSVNDTwotIFBPVEVOQ0lBTCBERSBBR0lUQcOHw4NPIExPQ0FMOiBBTFRPCi0gUklTQ08gw4AgT1JERU0gUMOaQkxJQ0E6IE1PREVSQURPCi0gQ0FQQUNJREFERSBERSBNT0JJTElaQcOHw4NPOiBFTQpDUkVTQ0lNRU5UTwotLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLQo+IEHDh8OVRVMgUkVDT01FTkRBREFTCi0gQVVNRU5UQVIgTU9OSVRPUkFNRU5UTyBFTEVUUsOUTklDTwooVEVMRUZPTklBIEUgQ09SUkVTUE9ORMOKTkNJQSkKLSBBVVRPUklaQVIgSU5GSUxUUkHDh8ODTyBERSBBR0VOVEUgTk8KR1JVUE8KLSBQUkVQQVJBUiBPUEVSQcOHw4NPIERFIERJU1NVQVPDg08sIENBU08KQSBBTUVBw4dBIEVTQ0FMT05FCi0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tCj4gQU5FWE9TCi0gUkVMQVTDk1JJTyBGT1RPR1LDgUZJQ08gQ8OTRC4gQU5YLTEyN0EKLSBUUkFOU0NSScOHw4NPIERFIEVTQ1VUQVMgQ8OTRC4gQU5YLTEyN0IKLSBNQVBBIERFIFJFTEHDh8OVRVMgRVNUUlVUVVJBSVMgRE8KR1JVUE8gQ8OTRC4gQU5YLTEyN0MKLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0KRklNIERPIFJFR0lTVFJPCi0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tCjMuMS4gUGFyw6JtZXRybyBbSURdIG91IFtWXW9sdGFyOgo=")))
		if ( logg.toUpperCase() == "INQ-024/H/66") {
			texto = "--------------------------------------\n> IDENTIFICAÇÃO\n- ID: INQ-024/H/66\n- TIPO DE OCORRÊNCIA: HOMICÍDIO\n- DATA DO FATO: 12/11/1966\n- INQUÉRITO INSTALADO: 12/11/1966\n- LOCAL: PRAIA DO CASSINO,  CENTRO  DE\nTREINAMENTO DO  7º GRUPO DE ARTILHARIA\nDE COSTA MOTORIZADO, RIO GRANDE – RS\n- CLASSIFICAÇÃO: INQUÉRITO CIVIL\n- RESPONSÁVEL:\n1. ZANKO, GASPAR. INSPETOR POLÍCIA\nCIVIL - RS.\n======================================\n           [ EM ANDAMENTO ]           \n======================================\n> RESUMO DA OCORRÊNCIA                \nCORPO  MASCULINO, ADULTO, IDENTIFICADO\nCOMO ADAM COLLINS, CIENTISTA  DA NASA,\nINTEGRANTE DA MISSÃO ECLIPSE NO BRASIL\nMORTO POR OBJETO PERFUROCORTANTE NA RE\nGIÃO DAS COSTAS. OBJETO NÃO ENCONTRADO\nNO LUGAR. OBJETOS DE VALOR EM POSSE DA\nVÍTIMA  DESCARTAM A  OPÇÃO DE ROUBO SE\nGUIDO DE MORTE.                       \n ======================================\n> ENTREVISTAS REALIZADAS              \n- FITAS   081/K/66 082/K/66 083/K/66  \n 084/K/66 085/K/66 086/K/66 087/K/66\n======================================\n> ANÁLISES TÉCNICAS REQUISITADAS      \n- ANÁLISE PAPILOSCÓPICA: 201/66       \n- ANÁLISE DO LEGISTA: 202/66         \n======================================\n> DILIGÊNCIAS REALIZADAS              \n- VISTORIA COMPLETA  NA ESTAÇÃO DE TRA\nBALHO 7. SEM RESULTADOS.              \n- BUSCA EM SUA RESIDÊNCIA. AGUARDANDO.\n======================================\n> CONCLUSÕES PRELIMINARES             \n- RELATÓRIO PRELIMINAR REL. 024/H1/66 \n======================================\n> OBSERVAÇÕES                         \n======================================\nTRANSMITIDO DOMUS: 25/11/1966 18H12MIN\n--------------------------------------\nFIM DO RELATÓRIO                      \n --------------------------------------\n3.1. Parâmetro [ID] ou [V]oltar:\n";
			writeText (output,texto);
		}
		else 
		if ( logg.toUpperCase() == "INQ-023/H/66") {	
			texto = "--------------------------------------\n> IDENTIFICAÇÃO\n- ID: INQ-023/H/66\n- TIPO DE OCORRÊNCIA: HOMICÍDIO\n- DATA DO FATO: 11/11/1966\n- INQUÉRITO INSTALADO: 12/11/1966\n- LOCAL: DOCAS ANTIGAS, PORTO DE RIO\nGRANDE, RIO GRANDE – RS\n- CLASSIFICAÇÃO: INQUÉRITO CIVIL\n- RESPONSÁVEL:\n1. ZANKO, GASPAR. INSPETOR POLÍCIA\nCIVIL - RS. DEPOIS,\n2. GREGÓRIO, ALENCAR. INSPETOR POLÍCIA\nCIVIL - RS.\n======================================\n           [ EM ANDAMENTO ]\n======================================\n> RESUMO DA OCORRÊNCIA\nCORPO MASCULINO, SEM IDENTIFICAÇÃO, EN\nCONTRADO BOIANDO NAS DOCAS DO PORTO DE\nRIO GRANDE PELO SOLDADO DA GUARDA, JOR\nGE AMARILDO DA SILVA, MATRÍCULA 121478\nFERIMENTOS POR ARMA DE FOGO NA  REGIÃO\nCRANIANA INDICAM EXECUÇÃO À CURTA  DIS\nTÂNCIA. SEM  DOCUMENTOS,  SEM  TESTEMU\nNHAS DIRETAS. CAIXA DE  MADEIRA  TRABA\nLHADA ENCONTRADA  BOIANDO PERTO DO COR\nPO.\n======================================\n> ENTREVISTAS REALIZADAS\n* REGISTROS NÃO ENCONTRADOS *\n======================================\n> ANÁLISES TÉCNICAS REQUISITADAS\n- PERÍCIA BALÍSTICA: 197/66\n- ANÁLISE PAPILOSCÓPICA: 199/66\n- ANÁLISE DO LEGISTA: 200/66\n======================================\n> DILIGÊNCIAS REALIZADAS\n- VISTORIA COMPLETA  NO PERÍMETRO. SEM\nSUCESSO.\n- LEVANTAMENTO DE MOVIMENTAÇÃO DE  VEÍ\nCULOS NAS  VIAS DE ACESSO  NAS ÚLTIMAS\n24H. SEM SUCESSO.\n- CONTATO COM A GUARDA MARINHA PARA VE\nRIFICAR  EMBARCAÇÕES E  TRIPULAÇÃO. EM\nANDAMENTO.\n======================================\n> CONCLUSÕES PRELIMINARES\n- ATÉ O MOMENTO  NÃO FOI POSSÍVEL IDEN\nTIFICAR A VÍTIMA.\n- ELEMENTOS INDICAM EXECUÇÃO DIRECIONA\nDA, REALIZADA POR AGENTE QUE  DESTRUIU\n AS FACES  DA VÍTIMA PARA  DIFICULTAR O\nRECONHECIMENTO.\n======================================\n> OBSERVAÇÕES\n- POSSÍVEL LIGAÇÃO COM O INQUÉRITO DO\nASSASSINATO NO PROJETO ECLIPSE AINDA\nNÃO CONFIRMADO.\n======================================\nTRANSMITIDO DOMUS: 18/11/1966 17H20MIN\n--------------------------------------\nFIM DO RELATÓRIO\n--------------------------------------\n3.1. Parâmetro [ID] ou [V]oltar:\n";
		writeText (output,texto)
			
        }
		else { 
		    writeText(output,">> PROCURANDO.......\n>> ERRO 404: NENHUM REGISTRO \n             COMPATÍVEL ENCONTRADO.\n>> VERIFIQUE OS DADOS INSERIDOS E\n             TENTE NOVAMENTE.\n--------------------------------------\n3.1. Parâmetro [ID] ou [V]oltar:\n")
			playSound("ERROR");
		}
   }

async function processConsultaPessoa(logg) {
	    if ( logg.toLowerCase() === "v" ) {
			consulta = false
			output.innerHTML = ''
		    hierarquiaMenu = 2;
			writeText(output, mostrarConsultaPessoas())
			return
		}
		//const logHASH = await sha256(logg.toLowerCase());
		if (logg.toUpperCase() == "BARBOSA") {
			texto = "--------------------------------------\n> IDENTIFICAÇÃO\n- ID: MATRÍCULA 017238\n- NOME: ALCEBÍADES BARBOSA\n- DATA DE NASC.: 04/11/1942\n- NACIONALIDADE: BRASILEIRA\n- OM DE ORIGEM: 6º BATALHÃO DA POLÍCIA\nDO EXÉRCITO\n- POSTO/GRADUAÇÃO: MAJOR\n--------------------------------------\n> DADOS PESSOAIS\n- NATURALIDADE: FORTALEZA – CE\n- CPF: 031.452.178-00\n- RG MILITAR: 17.238-6\n-GRUPO SANGUÍNEO: O+\n- ESTADO CIVIL: CASADO\n- ENDEREÇO: RUA GENERAL OSÓRIO, Nº 175,\nRIO GRANDE – RS\n--------------------------------------\n> HISTÓRICO FUNCIONAL\n- 1960 – INCORPORAÇÃO – CENTRO DE \nPREPARAÇÃO DE OFICIAIS (CPO-RJ)\n- 1962 – ASPIRANTE – 2º REGIMENTO DE\nINFANTARIA – SP\n- 1963 – PROMOVIDO A TENENTE\n- 1964 – CURSO DE OPERAÇÕES  ESPECIAIS\nNO  CENTRO  DE  INSTRUÇÃO DE GUERRA NA\nSELVA\n- 1965 – PROMOVIDO A MAJOR\n--------------------------------------\n> REGISTROS DISCIPLINARES\n- NENHUMA OCORRÊNCIA NEGATIVA\n- ELOGIO EM BOLETIM – MISSÃO PANTANAL\n(1962)\n--------------------------------------\n> ENVOLVIMENTO EM OPERAÇÕES SENSÍVEIS\n- OPERAÇÃO SUL-AMÉRICA – CLASSIFICADO\n(1966)\n--------------------------------------\n> OBSERVAÇÕES DE CONTRAINTELIGÊNCIA\n- PERFIL: LEAL, ESTRATÉGICO, ALTO GRAU\nDE SIGILO\n- NENHUM INDÍCIO DE VULNERABILIDADE  A\nINFILTRAÇÃO\n- ACOMPANHAMENTO PERIÓDICO RECOMENDADO\n--------------------------------------\n> REGISTROS BIOMÉTRICOS\n- IMPRESSÕES DIGITAIS: ARMAZENADAS\n(HASH 9FC12A67D3B98E)\n- PERFIL DE VOZ: COLETADO EM 15/02/64\n- ASSINATURA FÍSICA: MICROFILME\n741.211.A\n--------------------------------------\nFIM DO REGISTRO\n--------------------------------------\n1.1. Parâmetro [Nome] ou [V]oltar:\n"
			writeText (output,texto)
        }
		else { 
		    writeText(output,">> PROCURANDO.......\n>> ERRO 404: NENHUM REGISTRO \n             COMPATÍVEL ENCONTRADO.\n>> VERIFIQUE OS DADOS INSERIDOS E\n             TENTE NOVAMENTE.\n--------------------------------------\n.1. Parâmetro [Nome] ou [V]oltar:\n")
			playSound("ERROR");
		}
    }
	

async function processConsultaID(logg) {
	    if ( logg.toLowerCase() === "v" ) {
			consultaID = false
			output.innerHTML = ''
		    hierarquiaMenu = 2;
			writeText(output, mostrarConsultaPessoas())
			return
		}
		//const logHASH = await sha256(logg);
		if ((logg.toUpperCase() == "17.238-6")||(logg.toUpperCase() == "172386")) {
			texto = "--------------------------------------\n> IDENTIFICAÇÃO\n- ID: MATRÍCULA 017238\n- NOME: ALCEBÍADES BARBOSA\n- DATA DE NASC.: 04/11/1942\n- NACIONALIDADE: BRASILEIRA\n- OM DE ORIGEM: 6º BATALHÃO DA POLÍCIA\nDO EXÉRCITO\n- POSTO/GRADUAÇÃO: MAJOR\n--------------------------------------\n> DADOS PESSOAIS\n- NATURALIDADE: FORTALEZA – CE\n- CPF: 031.452.178-00\n- RG MILITAR: 17.238-6\n-GRUPO SANGUÍNEO: O+\n- ESTADO CIVIL: CASADO\n- ENDEREÇO: RUA GENERAL OSÓRIO, Nº 175,\nRIO GRANDE – RS\n--------------------------------------\n> HISTÓRICO FUNCIONAL\n- 1960 – INCORPORAÇÃO – CENTRO DE \nPREPARAÇÃO DE OFICIAIS (CPO-RJ)\n- 1962 – ASPIRANTE – 2º REGIMENTO DE\nINFANTARIA – SP\n- 1963 – PROMOVIDO A TENENTE\n- 1964 – CURSO DE OPERAÇÕES  ESPECIAIS\nNO  CENTRO  DE  INSTRUÇÃO DE GUERRA NA\nSELVA\n- 1965 – PROMOVIDO A MAJOR\n--------------------------------------\n> REGISTROS DISCIPLINARES\n- NENHUMA OCORRÊNCIA NEGATIVA\n- ELOGIO EM BOLETIM – MISSÃO PANTANAL\n(1962)\n--------------------------------------\n> ENVOLVIMENTO EM OPERAÇÕES SENSÍVEIS\n- OPERAÇÃO SUL-AMÉRICA – CLASSIFICADO\n(1966)\n--------------------------------------\n> OBSERVAÇÕES DE CONTRAINTELIGÊNCIA\n- PERFIL: LEAL, ESTRATÉGICO, ALTO GRAU\nDE SIGILO\n- NENHUM INDÍCIO DE VULNERABILIDADE  A\nINFILTRAÇÃO\n- ACOMPANHAMENTO PERIÓDICO RECOMENDADO\n--------------------------------------\n> REGISTROS BIOMÉTRICOS\n- IMPRESSÕES DIGITAIS: ARMAZENADAS\n(HASH 9FC12A67D3B98E)\n- PERFIL DE VOZ: COLETADO EM 15/02/64\n- ASSINATURA FÍSICA: MICROFILME\n741.211.A\n--------------------------------------\nFIM DO REGISTRO\n--------------------------------------\n1.1. Parâmetro [Nome] ou [V]oltar:\n"
			writeText (output,texto)
        }
		else { 
		    writeText(output,">> PROCURANDO.......\n>> ERRO 404: NENHUM REGISTRO \n             COMPATÍVEL ENCONTRADO.\n>> VERIFIQUE OS DADOS INSERIDOS E\n             TENTE NOVAMENTE.\n--------------------------------------\n1.2. Parâmetro [ID] ou [V]oltar:\n")
			playSound("ERROR");
		}
    }

async function processATPorID(logg) {
	    if ( logg.toLowerCase() === "v" ) {
			consultaATID = false
			output.innerHTML = ''
		    hierarquiaMenu = 6;
			writeText(output, mostrarAnalisesTecnicas())
			return
		}
		//const logHASH = await sha256(logg.toLowerCase());
		if ( logg == "197/66" ) {
		//if (logHASH === "69e0f3e1123ba3f6cf3eb4668af4fe506c539fb6305df9a6a9a1892155c87e62") {
			texto = "--------------------------------------\n|  REL. ANÁLISE TÉCNICO-LABORATORIAL |\n--------------------------------------\n> ANALISTA: SILVEIRA, ANTÔNIO MARCOS\n> SUBSISTEMA: MÓDULO DE ANÁLISE V2.1\n======================================\n> IDENTIFICAÇÃO\n- ID: 197/66\n- INQ: INQ-023/H/66\n> REFERÊNCIA: BALÍSTICA FORENSE\n  TERMINAL\n> COLETA: 12/11/1966\n> LOCAL: NECROTÉRIO - SANTA CASA DE\n  RIO GRANDE\n> REQUISITANTE: GREGÓRIO, ALENCAR.\n======================================\n> DESCRIÇÃO DA AMOSTRA\n- TRATA-SE DE CADÁVER HUMANO DO SEXO\nMASCULINO, ADULTO, APARENTEMENTE ENTRE\n35 E 45 ANOS, ENCAMINHADO AO INSTITUTO\nMÉDICO LEGAL SEM IDENTIFICAÇÃO FORMAL.\nO CORPO  APRESENTA ESTADO GERAL DE CON\nSERVAÇÃO COMPATÍVEL COM TEMPO DE MORTE\nINFERIOR A 24 HORAS APÓS A DESCOBERTA,\nSEM SINAIS DE PUTREFAÇÃO AVANÇADA.\nFORAM OBSERVADAS  TRÊS PERFURAÇÕES POR\nPROJÉTIL  DE ARMA DE FOGO NA REGIÃO FA\nCIAL, COM  AUSÊNCIA DE PROJÉTEIS  RETI\nDOS.  OS FERIMENTOS  PROVOCARAM GRANDE\nDESTRUIÇÃO DOS TECIDOS MOLES  DA FACE,\nFRATURAS MÚLTIPLAS DOS OSSOS MAXILARES\nE FRONTAIS, TORNANDO IMPOSSÍVEL O RECO\nNHECIMENTO VISUAL DA VÍTIMA.\n======================================\n> ANÁLISE\n1. ORIFÍCIOS DE ENTRADA COM BORDAS  RE\nGULARES E  EVERSÃO  MÍNIMA,  INDICANDO\nDISPARO DE CURTA A MÉDIA DISTÂNCIA.\n2. AUSÊNCIA DE ZONAS DE  ESFUMAÇAMENTO\nVISÍVEIS EXTERNAMENTE.\n3. PRESENÇA DE FRATURAS RADIAIS E FRAG\nMENTAÇÃO  ÓSSEA TÍPICA DE  IMPACTOS DE\nALTA VELOCIDADE.\n4. TRAJETÓRIAS CONVERGENTES,  DE  FRON\nTAL PARA POSTERIOR,  COM LEVE  INCLINA\nÇÃO  SUPERIOR, SUGERINDO QUE  OS DISPA\nROS OCORRERAM COM  A VÍTIMA EM POSIÇÃO\nERETA.\n5. PEQUENOS  FRAGMENTOS  METÁLICOS NAS\nCAVIDADES ÓSSEAS FACIAIS,  COMPATÍVEIS\nCOM PROJÉTEIS DE PEQUENO CALIBRE.\n6. A EXTENSÃO DOS DANOS ÓSSEOS E A DIS\nPERSÃO DOS FRAGMENTOS SUGEREM  ENERGIA\nCINÉTICA MÉDIA A ALTA, COM  CARACTERÍS\nTICAS BALÍSTICAS COMPATÍVEIS COM PROJÉ\nTEIS CALIBRE 9MM.\n======================================\n> OUTROS ELEMENTOS\n1. NENHUM PROJÉTIL  ÍNTEGRO FOI  ENCON\nTRADO NO CORPO.\n2. A POSIÇÃO DOS DISPAROS E OS ÂNGULOS\nSUGEREM EXECUÇÃO A CURTA DISTÂNCIA,COM\nPOSSÍVEL INTENÇÃO DE DESFIGURAÇÃO.\n======================================\n> CONCLUSÃO\n- COM BASE NAS CARACTERÍSTICAS MORFOLÓ\nGICAS DAS LESÕES, NA ANÁLISE DOS  FRAG\nMENTOS METÁLICOS E  NOS PADRÕES DE FRA\nTURA ÓSSEA, CONCLUI-SE QUE OS  FERIMEN\nTOS  FORAM CAUSADOS  POR  ARMA DE FOGO\nCOMPATÍVEL COM MUNIÇÃO CALIBRE 9MM.\n- O PADRÃO DE LESÕES INDICA TRÊS DISPA\nROS DIRIGIDOS INTENCIONALMENTE  AO ROS\nTO, A CURTA DISTÂNCIA, COM  DESTRUIÇÃO\nFACIAL EXTENSIVA, PROVAVELMENTE  COM O\nINTUITO DE INVIABILIZAR O RECONHECIMEN\nTO DA VÍTIMA.\n--------------------------------------\nFIM DO RELATÓRIO\n--------------------------------------\n4.1. Parâmetro [ID] ou [V]oltar:\n";
			//texto =decodeURIComponent(escape(atob("LS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0KfCAgUkVMLiBBTsOBTElTRSBUw4lDTklDTy1MQUJPUkFUT1JJQUwgfAotLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLQo+IEFOQUxJU1RBOiBHVUVERVMsIFNHVC4gU0XDh8ODTyBYVkkgUlMKPiBTVUJTSVNURU1BOiBNw5NEVUxPIERFIEFOw4FMSVNFIFYzLjkKPT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT0KPiBSRUZFUsOKTkNJQTogQU1PU1RSQSBNSU5FUkFMCj4gQ09MRVRBOiAxMi8wNC8xOTY4Cj4gTE9DQUw6IEdVQVJJVEFTIOKAkyBDQcOHQVBBVkEgRE8gU1VML1JTCj4gUkVRVUlTSVRBTlRFOiBaQU5LTywgR0FTUEFSLgo9PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PQo+IERFU0NSScOHw4NPIERBIEFNT1NUUkEKLSBNQVRFUklBTDogUk9DSEEgTUVUQU3Dk1JGSUNBCi0gTUFTU0EgVE9UQUwgQU5BTElTQURBOiAxLDIzIEtHCi0gQVNQRUNUTzogQ09SIENJTlpBLUVTVkVSREVBREEsIENPTQogIFZFSU9TIEFNQVJFTEFET1MKPT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT0KPiBBTsOBTElTRSBRVcONTUlDQSBFIE1JTkVSQUzDk0dJQ0EKLSBURVNURVMgREUgRkxVT1JFU0PDik5DSUEg4oCTIFJFU1VMVEFETwogIFBPU0lUSVZPIFBBUkEgRUxFTUVOVE9TIFJBRElPQVRJVk9TCi0gRVNQRUNUUk9NRVRSSUEgREUgTUFTU0Eg4oCTIERFVEVDw4fDg08KICBERSBJU8OTVE9QT1MgREUgVVLDgk5JTyAoVS0yMzgvVS0yMzUpCi0gQU7DgUxJU0UgREUgRElGUkHDh8ODTyBERSBSQUlPUy1YCiAgUEFEUsODTyBDT05TSVNURU5URSBDT00gVVJBTklOSVRBCj09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09Cj4gT1VUUk9TIEVMRU1FTlRPUwotIE7Dg08gSURFTlRJRklDQURBIFBSRVNFTsOHQSBERToKICAqIENPQlJFIChDdSkg4oCTIEFCQUlYTyBETyBMSU1JVEUKICAqIFpJTkNPIChabikg4oCTIEFVU0VOVEUKICAqIENIVU1CTyhQYikg4oCTIFRSQcOHT1MgTUVOT1JFUwo9PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PQo+IENPTkNMVVPDg08KLSBBTU9TVFJBIENPTVBBVMONVkVMIENPTSBST0NIQQogIFVSQU7DjUZFUkEgREUgQkFJWEEgQ09OQ0VOVFJBw4fDg08KLSBQUkVTRU7Dh0EgREUgVVLDgk5JTyBOQVRVUkFMCi0gUkVDT01FTkRBLVNFIEFWQUxJQcOHw4NPIEdFT0zDk0dJQ0EKICBBTVBMSUFEQSBEQSDDgVJFQQotLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLQpGSU0gRE8gUkVMQVTDk1JJTwotLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLQo0LjIuIFBhcsOibWV0cm8gW0lEXSBvdSBbVl1vbHRhcjoK")))
			writeText (output,texto)
        }
		else 
		if ( logg == "200/66" ) {
		//if (logHASH === "00db42b9007471d2ce5ce6281ec7b121ab07a366e93f25310da72098b2806d41") {
		//	texto =decodeURIComponent(escape(atob("LS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0KfCAgUkVMLiBBTsOBTElTRSBUw4lDTklDTy1MQUJPUkFUT1JJQUwgfAotLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLQo+IEFOQUxJU1RBOiBHVUVERVMsIFNHVC4gU0XDh8ODTyBYVkkgUlMKPiBTVUJTSVNURU1BOiBNw5NEVUxPIERFIEFOw4FMSVNFIFYzLjkKPT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT0KPiBSRUZFUsOKTkNJQTogQU1PU1RSQSBMw41RVUlEQQo+IENPTEVUQTogMTIvMDQvMTk2OAo+IExPQ0FMOiBHVUFSSVRBUyDigJMgQ0HDh0FQQVZBIERPIFNVTC9SUwo+IFJFUVVJU0lUQU5URTogWkFOS08sIEdBU1BBUi4KPT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT0KPiBERVNDUknDh8ODTyBEQSBBTU9TVFJBCi0gTUFURVJJQUw6IEzDjVFVSURPIFZPTMOBVElMCiAgICAgICAgICAgIFRSQU5TUEFSRU5URQotIFZPTFVNRSBUT1RBTCBBTkFMSVNBRE86IDc1MCBNTAotIEFTUEVDVE86ICBPRE9SIENBUkFDVEVSw41TVElDTyBERQogICAgICAgICAgICBDT01CVVNUw41WRUwsIElOQ09MT1IKPT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT0KPiBBTsOBTElTRSBGw41TSUNPLVFVw41NSUNBCi0gVEVTVEUgREUgUE9OVE8gREUgRlVMR09SOiAxNcKwQwotIENST01BVE9HUkFGSUEgR0FTT1NBOiBQRVJGSUwgREUKICBISURST0NBUkJPTkVUT1MgREUgQ0FERUlBIENVUlRBCi0gVEVTVEUgREUgREVTVElMQcOHw4NPOiBGQUlYQSBERSA2MMKwQyBBCiAgMTQwwrBDCi0gREVURUPDh8ODTyBERSBBRElUSVZPUyBBTlRJQ09OR0VMQU5URVMKICBFIEFOVElERVRPTkFOVEVTCj09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09Cj4gQ09NUEFSQcOHw4NPIENPTSBQQURSw5VFUwotIFBFUkZJTCBJREVOVElGSUNBRE8gQ09NUEFUw41WRUwgQ09NOgogICogR0FTT0xJTkEgREUgQVZJQcOHw4NPIEFWR0FTIDEwMC8xMzAKPT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT0KPiBPVVRST1MgRUxFTUVOVE9TCiAgKiBOw4NPIFNFIFRSQVRBIERFIFFVRVJPU0VORSBERQogICAgQVZJQcOHw4NPIChKRVQgQSkKICAqIE7Dg08gw4kgU09MVkVOVEUgSU5EVVNUUklBTAogICogTsODTyDDiSBDT01CVVNUw41WRUwgQVVUT01PVElWTyBDT01VTQo9PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PQo+IENPTkNMVVPDg086Ci0gQ09ORklSTUEtU0UgQSBQUkVTRU7Dh0EgREUgR0FTT0xJTkEKICBERSBBVklBw4fDg08gKEFWR0FTKQotIElORElDQcOHw4NPIERFIFVTTyBSRUxBQ0lPTkFETyBBCiAgQVRJVklEQURFUyBBw4lSRUFTCi0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tCkZJTSBETyBSRUxBVMOTUklPCiAtLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLQo0LjIuIFBhcsOibWV0cm8gW0lEXSBvdSBbVl1vbHRhcjoK")))
			texto = "--------------------------------------\n|  REL. ANÁLISE TÉCNICO-LABORATORIAL |\n--------------------------------------\n> ANALISTA: ANDRADAS, ANTONIO MARIA\n> SUBSISTEMA: MÓDULO DE ANÁLISE V7.1\n======================================\n> IDENTIFICAÇÃO\n- ID: 200/66\n- INQ: INQ-023/H/66\n> REFERÊNCIA:  RELATÓRIO LEGISTA PRELI\n  MINAR\n> COLETA: 13/11/1966\n> LOCAL: NECROTÉRIO - SANTA CASA DE\n  RIO GRANDE\n> REQUISITANTE: GREGÓRIO, ALENCAR.\n======================================\n> DESCRIÇÃO DA AMOSTRA\nCADÁVER HUMANO DO SEXO MASCULINO,  COM\nIDADE ESTIMADA ENTRE 35 E 45  ANOS, ES\nTATURA MEDIANA (ENTRE 1,68 M E 1,72 M)\nCOMPLEIÇÃO FÍSICA DE  LEVE  SOBREPESO,\nCOM DISCRETA PROTUBERÂNCIA  ABDOMINAL.\nPELE CLARA, PARCIALMENTE MACERADA PELA\nIMERSÃO  EM ÁGUA CONTAMINADA.  CABELOS\nRALOS, DE COLORAÇÃO CLARA; PRESENÇA DE\nCALVÍCIE FRONTAL AVANÇADA.\nA FACE APRESENTA EXTENSA DESTRUIÇÃO TE\nCIDUAL PROVOCADA POR TRÊS  PERFURAÇÕES\nPOR PROJÉTIL DE ARMA DE  FOGO,  CONCEN\nTRADAS NA REGIÃO  FRONTAL  E NASAL,  O\nQUE INVIABILIZA O  RECONHECIMENTO VISU\nAL DA VÍTIMA. O CADÁVER FOI  RESGATADO\nEM CANAL POLUÍDO PRÓXIMO ÀS DOCAS, COM\nTEMPO ESTIMADO DE SUBMERSÃO  ENTRE 6 E\n10 HORAS, CONSIDERANDO GRAU DE  MACERA\nÇÃO E PRESENÇA DE LARVAS AQUÁTICAS.\nDENTIÇÃO PRESERVADA, SEM PERDAS EVIDEN\nTES. UNHAS LIMPAS, SEM SINAIS DE  LUTA\nCORPORAL.\n======================================\n> ANÁLISE\nA AUTÓPSIA REVELA AUMENTO DO VOLUME HE\nPÁTICO E COLORAÇÃO AMARELADA,  SUGERIN\nDO ESTEATOSE HEPÁTICA EM ESTÁGIO  MODE\nRADO A AVANÇADO. A TEXTURA FRIÁVEL E A\nCONGESTÃO DO ÓRGÃO INDICAM  COMPROMETI\nMENTO FUNCIONAL CRÔNICO, POSSIVELMENTE\nLIGADO A USO PROLONGADO DE SUBSTÂNCIAS\nHEPATOTÓXICAS, COMO O ÁLCOOL.\nEXAMES TOXICOLÓGICOS INICIAIS  DETECTA\nRAM RESÍDUOS COMPATÍVEIS COM  BENZODIA\nZEPÍNICOS, SUGERINDO USO  HABITUAL  DE\nTRANQUILIZANTES OU  HIPNÓTICOS.  VESTÍ\nGIOS DO FÁRMACO TAMBÉM FORAM  ENCONTRA\nDOS NO CONTEÚDO GÁSTRICO, INDICANDO IN\nGESTÃO RECENTE.\nA CAUSA DA MORTE FOI  TRAUMATISMO  CRÂ\nNIO-FACIAL POR PROJÉTEIS DE ARMA DE FO\nGO EM CURTA DISTÂNCIA, COM  LESÕES  FA\nTAIS IMEDIATAS E PERDA EXTENSA DE  MAS\nSA ENCEFÁLICA. O AFUNDAMENTO POSTERIOR\nFOI PASSIVO.\n======================================\n> OUTROS ELEMENTOS\n1. PRESENÇA DE LARVAS DE INSETOS  AQUÁ\nTICOS NOS ORIFÍCIOS DE  ENTRADA, COMPA\nTÍVEIS COM AMBIENTE POLUÍDO.\n2. CORAÇÃO COM LEVE  HIPERTROFIA;  PUL\nMÕES CONGESTOS.\n3. AUSÊNCIA DE TATUAGEN E IMPLANTES.  \n4. NENHUM SINAL EVIDENTE DE LUTA CORPO\nRAL OU CONTENÇÃO FÍSICA.\n5. SEM CICATRIZES  ANTIGAS  OU  ALTERA\nÇÕES ÓSSEAS PRÉVIAS.\n======================================\n> CONCLUSÃO\nO CADÁVER CORRESPONDE A  UM  INDIVÍDUO\nDO SEXO MASCULINO, ENTRE 35 E 45 ANOS,\nDE PROVÁVEL ORIGEM OU DESCENDÊNCIA  EU\nROPEIA, COM USO CRÔNICO  DE  TRANQUILI\nZANTES E DOENÇA HEPÁTICA  AVANÇADA POR\nPROVÁVEL EXPOSIÇÃO  PROLONGADA A  SUBS\nTÂNCIAS TÓXICAS.\nO PADRÃO DE LESÕES FACIAIS  INDICA EXE\nCUÇÃO DELIBERADA POR ARMA DE FOGO, COM\nOBJETIVO CLARO DE IMPEDIR RECONHECIMEN\nTO. A PERMANÊNCIA EM CANAL CONTAMINADO\nPÓS-MORTE ACELEROU A  DEGRADAÇÃO  TECI\nDUAL E COMPROMETEU VESTÍGIOS COMPLEMEN\nTARES.\n--------------------------------------\nFIM DO RELATÓRIO\n--------------------------------------\n4.1. Parâmetro [ID] ou [V]oltar:\n";
			writeText (output,texto)
		}
		else
		if ( logg == "199/66") {
			texto = "--------------------------------------\n| RELATÓRIO COMPARAÇÃO DE IMPRESSÕES |\n--------------------------------------\n> ANALISTA: MONTOVANI, LARISSA. SETOR\nDE IDENTIFICAÇÃO BIOMÉTRICA\n> SUBSISTEMA: MÓDULO DE BIOMETRIA V0.9\n======================================\n> IDENTIFICAÇÃO\n- ID: 199/66\n- INQ: INQ-023/H/66\n> REFERÊNCIA: ANÁLISE PAPILOSCÓPICA\n> COLETA: 12/11/1966\n> LOCAL: NECROTÉRIO - SANTA CASA DE\n  RIO GRANDE\n> REQUISITANTE: GREGÓRIO, ALENCAR.\n======================================\n> INDIVÍDUO 1: DEDO INDICADOR DIREITO\n> HASH: B8IOFE983092AA23\n> MINÚCIAS REGISTRADAS (5 DESTAQUES):\n  ID   TIPO       COORD X   COORD Y\n  001  TERMINAÇÃO 185       220\n  002  BIFURCAÇÃO 090       180\n  003  ILHA       123       238\n  004  TERMINAÇÃO 077       099\n  005  BIFURCAÇÃO 047       112\n--------------------------------------\n> BASES CONSULTADAS\n- POLÍCIA CIVIL DO RS: SEM RESULTADO\n- POLÍCIA CIVIL DE SC: EM ANÁLISE\n- POLÍCIA CIVIL DO PR: SEM RESULTADO\n- POLÍCIA CIVIL DO RJ: EM ANÁLISE\n- POLÍCIA CIVIL DE SP: EM ANÁLISE\n- EXÉRCITO BRASILEIRO: CONFIDENCIAL\n- MARINHA DO BRASIL: CONFIDENCIAL\n- PORTOS DO BRASIL: EM ANÁLISE\n======================================\n> SITUAÇÃO ATUAL\n- INDIVÍDUO NÃO ENCONTRADO.\n- DATA: 18/11/1966\n--------------------------------------\nFIM DO RELATÓRIO\n--------------------------------------\n4.1. Parâmetro [ID] ou [V]oltar:\n";
			writeText (output,texto)
		}
		else 
		if ( logg == "201/66") {
			texto = "--------------------------------------\n| RELATÓRIO COMPARAÇÃO DE IMPRESSÕES |\n--------------------------------------\n> ANALISTA: MONTOVANI, LARISSA. SETOR\nDE IDENTIFICAÇÃO BIOMÉTRICA\n> SUBSISTEMA: MÓDULO DE BIOMETRIA V0.9\n======================================\n> IDENTIFICAÇÃO\n- ID: 201/66\n- INQ: INQ-024/H/66\n> REFERÊNCIA: ANÁLISE PAPILOSCÓPICA\n> COLETA: 14/11/1966\n> LOCAL: NECROTÉRIO - SANTA CASA DE\n  RIO GRANDE\n> REQUISITANTE: ZANKO, GASPAR.\n======================================\n> INDIVÍDUO 1: DEDO INDICADOR DIREITO\n> NOME: ADAM COLLINS\n> HASH: 918AB739C8D721B\n> MINÚCIAS REGISTRADAS (5 DESTAQUES):\n  ID   TIPO       COORD X   COORD Y\n  001  TERMINAÇÃO 077       230\n  002  BIFURCAÇÃO 021       179\n  003  ILHA       145       154\n  004  TERMINAÇÃO 012       048\n  005  BIFURCAÇÃO 128       194\n--------------------------------------\n> BASES CONSULTADAS\n- OPERAÇÃO CANCELADA PELO OPERADOR\n- OBS: IDENTIDADE CONFIRMADA POR DADOS\nENVIADOS PELA EMBAIXADA  NORTE-AMERICA\nNA NO BRASIL.\n======================================\n> SITUAÇÃO ATUAL\n- IDENTIFICAÇÃO: ADAM COLLINS.\n- DATA: 16/11/1966\n--------------------------------------\nFIM DO RELATÓRIO\n--------------------------------------\n4.1. Parâmetro [ID] ou [V]oltar:\n";
			writeText (output,texto)
		}
		else 
		if ( logg == "202/66" ) {
			texto = "--------------------------------------\n|  REL. ANÁLISE TÉCNICO-LABORATORIAL |\n--------------------------------------\n> ANALISTA: ANDRADAS, ANTONIO MARIA\n> SUBSISTEMA: MÓDULO DE ANÁLISE V7.1\n======================================\n> IDENTIFICAÇÃO\n- ID: 202/66\n- INQ: INQ-024/H/66\n> REFERÊNCIA:  RELATÓRIO LEGISTA PRELI\n  MINAR\n> COLETA: 13/11/1966\n> LOCAL: NECROTÉRIO - SANTA CASA DE\n  RIO GRANDE\n> REQUISITANTE: ZANKO, GASPAR.\n======================================\n> DESCRIÇÃO DA AMOSTRA\nCORPO MASCULINO, ADULTO,  IDENTIFICADO\nCOMO ADAM COLLINS, NACIONALIDADE NORTE\nAMERICANA,  CIENTISTA VINCULADO À NASA\nE INTEGRANTE  DA MISSÃO ECLIPSE NO BRA\nSIL. CAUCASIANO, ENTRE 38 E 42 ANOS,CA\nBELOS LISOS CORTADOS, BIGODE RALO.A VÍ\nTIMA  APRESENTAVA-SE  EM DECÚBITO  VEN\nTRAL, TRAJANDO  CAMISA  SOCIAL  BRANCA\nCOM PERFURAÇÃO ÚNICA NAS  COSTAS.  NÃO\nHAVIA SINAIS DE LUTA CORPORAL OU ARRAS\nTO.\n======================================\n> ANÁLISE\nVERIFICA-SE ÚNICA LESÃO  PERFUROCORTAN\nTE NA REGIÃO DORSAL ESQUERDA,  INTERES\nCAPULAR,  COM  BORDAS LIMPAS, INDICATI\nVAS DE OBJETO AFIADO DE LÂMINA REGULAR\nE PENETRANTE. A PROFUNDIDADE DA FERIDA\nSUGERE FORÇA DIRECIONADA E  CONHECIMEN\nTO ANATÔMICO MÍNIMO.  A AUSÊNCIA DE OU\nTRAS LESÕES EXTERNAS  INDICA ATAQUE SÚ\nBITO E CERTEIRO. O SANGRAMENTO ABUNDAN\nTE E CONCENTRADO  AO REDOR DA  PERFURA\nÇÃO DEMONSTRA QUE A  VÍTIMA AINDA ESTA\nVA VIVA NO MOMENTO DA AGRESSÃO.\n======================================\n> OUTROS ELEMENTOS\n1. NÃO FORAM LOCALIZADOS O INSTRUMENTO\nPERFURANTE NEM QUAISQUER  INDÍCIOS  DE\nRESISTÊNCIA POR PARTE DA VÍTIMA.\n2. CONDIÇÕES AMBIENTAIS E  LOCALIZAÇÃO\nDO CORPO (EM ÁREA ARENOSA) NÃO INTERFE\nRIRAM  SIGNIFICATIVAMENTE  NA PRESERVA\nÇÃO DA CENA IMEDIATA.\n======================================\n> CONCLUSÃO\nMORTE CAUSADA POR INSTRUMENTO  PERFURO\nCORTANTE AINDA NÃO IDENTIFICADO, UTILI\nZADO COM PRECISÃO NAS COSTAS DA VÍTIMA\nAS  CARACTERÍSTICAS DA FERIDA  E O CON\nTEXTO DESCARTAM SUICÍDIO OU ACIDENTE.\nELEMENTOS  OBSERVADOS SÃO  COMPATÍVEIS\nCOM HOMICÍDIO DELIBERADO.\n--------------------------------------\nFIM DO RELATÓRIO\n--------------------------------------\n4.1. Parâmetro [ID] ou [V]oltar:\n";
			writeText (output,texto)
		}
		else { 
		    writeText(output,">> PROCURANDO.......\n>> ERRO 404: NENHUM REGISTRO \n             COMPATÍVEL ENCONTRADO.\n>> VERIFIQUE OS DADOS INSERIDOS E\n             TENTE NOVAMENTE.\n--------------------------------------\n4.1. Parâmetro [ID] ou [V]oltar:\n")
			playSound("ERROR");
		}
		
		
    }
	
async function processATImpressoes(logg) {
	    if ( logg.toLowerCase() === "v" ) {
			consultaATImpressoes = false
			output.innerHTML = ''
		    hierarquiaMenu = 6;
			writeText(output, mostrarAnalisesTecnicas())
			return
		}
		const logHASH = await sha256(logg.toUpperCase());
		if ((logHASH === "4cb72357d2b2fcaff2d0d6da001f5f153aa6715e75885e3ffd38a4c8980c5f10") ||
		    (logHASH === "3dd16255ddf7c24093076f4ea3826d8456e309f48bef60925de99e13a047744d"))
		    {
			texto =decodeURIComponent(escape(atob("LS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0KfCBSRUxBVMOTUklPIENPTVBBUkHDh8ODTyBERSBJTVBSRVNTw5VFUyB8Ci0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tCj4gQU5BTElTVEE6IFTDiUMuIDExNyDigJMgU0VUT1IgREUKSURFTlRJRklDQcOHw4NPIEJJT03DiVRSSUNBCj4gU1VCU0lTVEVNQTogTcOTRFVMTyBERSBCSU9NRVRSSUEgVjEuMgo9PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PQo+IElORElWw41EVU8gMTogREVETyBJTkRJQ0FET1IgRElSRUlUTwo+IEhBU0g6IEE5QjNGN0MyRTREMTg5NTcKPiBNSU7DmkNJQVMgUkVHSVNUUkFEQVMgKDUgREVTVEFRVUVTKToKICBJRCAgIFRJUE8gICAgICAgQ09PUkQgWCAgIENPT1JEIFkKICAwMDEgIFRFUk1JTkHDh8ODTyAxMjUgICAgICAgMjMwCiAgMDAyICBCSUZVUkNBw4fDg08gMTM4ICAgICAgIDI0NQogIDAwMyAgSUxIQSAgICAgICAxNDMgICAgICAgMjYwCiAgMDA0ICBURVJNSU5Bw4fDg08gMTUwICAgICAgIDI4MAogIDAwNSAgQklGVVJDQcOHw4NPIDE2MCAgICAgICAzMDAKLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0KPiBBTU9TVFJBIDI6IERFRE8gPwo+IEhBU0g6IEE5QjNGN0MyRTREMTg5NTkKPiBNSU7DmkNJQVMgUkVHSVNUUkFEQVMgKDUgREVTVEFRVUVTKToKICBJRCAgIFRJUE8gICAgICAgQ09PUkQgWCAgIENPT1JEIFkKICAwMDEgIFRFUk1JTkHDh8ODTyAxMjYgICAgICAgMjI5CiAgMDAyICBCSUZVUkNBw4fDg08gMTM5ICAgICAgIDI0NgogIDAwMyAgSUxIQSAgICAgICAxNDIgICAgICAgMjYxCiAgMDA0ICBURVJNSU5Bw4fDg08gMTUxICAgICAgIDI3OQogIDAwNSAgQklGVVJDQcOHw4NPIDE2MSAgICAgICAyOTkKPT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT0KPiBBTsOBTElTRSBERSBDT1JSRVNQT05Ew4pOQ0lBUwotLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLQogICAgICAgSU5ESVbDjURVTy4wMSBBTU9TVFJBLjAyICBTVEFUVVMKSUQgMDAxIFRFUk1JTkHDh8ODTyAgIFRFUk1JTkHDh8ODTyAgIFNJTQpJRCAwMDIgQklGVVJDQcOHw4NPICAgQklGVVJDQcOHw4NPICAgU0lNCklEIDAwMyBJTEhBICAgICAgICAgSUxIQSAgICAgICAgIFNJTQpJRCAwMDQgVEVSTUlOQcOHw4NPICAgVEVSTUlOQcOHw4NPICAgU0lNCklEIDAwNSBCSUZVUkNBw4fDg08gICBCSUZVUkNBw4fDg08gICBTSU0KLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0KVE9UQUwgREUgTUlOw5pDSUFTIEFOQUxJU0FEQVM6IDUKTUlOw5pDSUFTIENPUlJFU1BPTkRFTlRFUzogNQo9PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PQo+PiBDT05DTFVTw4NPClJFR0lTVFJPUyBDT01QQVTDjVZFSVMg4oCTIEFMVEEgUFJPQkFCSUwuCklERU5USURBREUgRE8gSU5ESVbDjURVTy4KSUQgRE8gSU5Ew41WSURVTyAwMTogMDI0NjcxCi0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tCkZJTSBETyBSRUxBVMOTUklPCi0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tCjQuMy4gUGFyw6JtZXRybyBbSEFTSF0gb3UgW1Zdb2x0YXI6Cg==")))
			writeText (output,texto)
        }
		else { 
		    writeText(output,">>> PROCURANDO.......\n>> ERRO 404: NENHUM REGISTRO \n             COMPATÍVEL ENCONTRADO.\n>> VERIFIQUE OS DADOS INSERIDOS E\n             TENTE NOVAMENTE.\n--------------------------------------\n4.3. Parâmetro [HASH] ou [V]oltar:\n")
		    playSound("ERROR");
		}
    }	

async function processAlertas(logg) {
	    if ( logg.toLowerCase() === "v" ) {
			consultAlertas = false
			output.innerHTML = ''
		    hierarquiaMenu = 1;
			writeText(output, mostrarMenuPrincipal())
			return
		}
	    //const logHASH = await sha256(logg.toLowerCase());
        if (logg.toUpperCase() == "11/11/1966") {
			texto = "--------------------------------------\nCOMUNICADO INTERNO - PRIORID. 3\n--------------------------------------\n> REFERÊNCIA: OCORRÊNCIA POLICIAL\n  PROXIMIDADES DE INSTALAÇÃO MILITAR\n> DATA: 11/11/1966\n> LOCAL: PRAIA DO CASSINO\n         RIO GRANDE - RS\n======================================\n> SUMÁRIO\n- REGISTRADO UM HOMICÍDIO NAS\n  IMEDIAÇÕES DO CENTRO DE TREINAMENTOS\n  DO 7º GRUPO DE ARTILHARIA DE COSTA\n  MOTORIZADO.\n- O CORPO DE UM INDIVÍDUO MASCULINO,\n  ADULTO, IDENTIFICADO COMO ADAM\n  COLLINS, FOI ENCONTRADO COM EVIDEN\n  TES SINAIS DE EXECUÇÃO COM O USO DE\n  UM OBJETO PERFURANTE NAS COSTAS.\n- OCORRÊNCIA DETECTADA POR TRANSEUNTES\n======================================\n> PROVIDÊNCIAS IMEDIATAS\n- ÁREA ISOLADA POLÍCIA DO EXÉRCITO\n- ACIONAMENTO DA POLÍCIA CIVIL\n- INVESTIGAÇÃO EM CURSO\n======================================\n> ORIENTAÇÃO:\n- MANTER SIGILO ABSOLUTO SOBRE O\n  OCORRIDO ATÉ SEGUNDA DETERMINAÇÃO.\n- AGUARDAR INSTRUÇÕES DA SEÇÃO DE\n  INTELIGÊNCIA REGIONAL (SIR/8ªRM).\n--------------------------------------\nFIM DO RELATÓRIO\n --------------------------------------\n5.1. Parâm. [dd/mm/aaaa] ou[V]oltar:\n";
			writeText (output,texto);
        }
		else 
		if (logg.toUpperCase() == "12/11/1966") {
			texto = "--------------------------------------\n>>           AVISO GERAL           <<\n--------------------------------------\nATUALIZAÇÃO NO CADASTRO DE ELEMENTOS\nSENSÍVEIS SERÁ PROCESSADO 22/11/1966\nSISTEMA SOFRERÁ INSTABILIDADE NO DIA\n--------------------------------------\n5.1. Parâm. [dd/mm/aaaa] ou[V]oltar:\n";
			writeText (output,texto);
        }
		else { 
		    writeText(output,">> PROCURANDO.......\n>> ERRO 404: NENHUM REGISTRO \n             COMPATÍVEL ENCONTRADO.\n>> VERIFIQUE OS DADOS INSERIDOS E\n             TENTE NOVAMENTE.\n--------------------------------------\n5.1. Parâm. [dd/mm/aaaa] ou [V]oltar:\n");
			playSound("ERROR");
		}
   }

async function processProjetos(logg) {
	    if ( logg.toLowerCase() === "v" ) {
			consultaProjetos = false
			output.innerHTML = ''
		    hierarquiaMenu = 1;
			writeText(output, mostrarMenuPrincipal())
			return
		}
	    //const logHASH = await sha256(logg.toLowerCase());
        if ((logg.toUpperCase() == "055")||
 		    (logg.toUpperCase() == "063") ||
			(logg.toUpperCase() == "065") ||
			(logg.toUpperCase() == "073") ||
			(logg.toUpperCase() == "077") ||
			(logg.toUpperCase() == "001") ||
			(logg.toUpperCase() == "042"))
			{
			texto =">> ERRO 004: ACESSO NEGADO.\n             PERMISSÃO INSUFICIENTE.\n--------------------------------------\nx.1. Parâmetro [ID] ou [V]oltar:\n";
			writeText (output,texto)
        }
		else 
		if (logg.toUpperCase() == "099")
			{
			texto = ">> ERRO 000: ERRO CRÍTICO.   TODAS AS\n        OPERAÇÕES FORAM INTERROMPIDAS.\nUsuário desconectado.\n--------------------------------------\nLogin:";
			login = true;
			senha = false; 
			user = 0;
			hierarquiaMenu = 1;
			output.innerHTML = '';
			consultaProjetos = false;
			writeText (output,texto)
        }
		else 
		if (logg.toUpperCase() == "666") {
			texto ="--------------------------------------\n|  PRJ. ARMAGEDOM                    |\n--------------------------------------\n> SITUAÇÃO: INATIVO                   \n======================================\n> INÍCIO\n- 18/09/1945\n- FAZENDA CRUZEIRO DO SUL, PORTO VELHO\n  TERRITÓRIO DE RONDÔNIA\n======================================\n> OPERADOR PRINCIPAL\n- R<)Gy[=v)+aa=>w)<\%<       [ IC|OBT ]\n> OPERADORES CIENTÍFICOS\n- #y[T6=>T\qTGT                  [ IC ]\n- T)wR=q+\fx+)q                   [ IC ]\n- \y<*=[R*yGf                    [ IC ]\n- R<)G=i<T)\T0               [ IC|OBT ]\n======================================\n> AVALIAÇÃO\nNÃO DISPONIVEL\n--------------------------------------\nIC|INFORMAÇÃO CLASSIFICADA    OB|ÓBITO\nDS|DESAPARECIDO  IG|IGNORADO  MT|MORTO\n--------------------------------------\nFIM DO RELATÓRIO\n--------------------------------------\nX.1. Parâmetro [ID] ou [V]oltar:\n";
			writeText (output,texto)
        }
		else { 
		    writeText(output,">> PROCURANDO.......\n>> ERRO 404: NENHUM REGISTRO \n             COMPATÍVEL ENCONTRADO.\n>> VERIFIQUE OS DADOS INSERIDOS E\n             TENTE NOVAMENTE.\n--------------------------------------\nX.1. Parâmetro [ID] ou [V]oltar:\n")
		    playSound("ERROR");
		}
   }

async function processOperacoes(logg) {
	    if ( logg.toLowerCase() === "v" ) {
			consultaOperacoes = false
			output.innerHTML = ''
		    hierarquiaMenu = 1;
			writeText(output, mostrarMenuPrincipal())
			return
		}
	    //const logHASH = await sha256(logg.toLowerCase());
        if (logg.toUpperCase() == "219") {
			texto = "--------------------------------------\n|  REL. OPERAÇÃO SENTINELA           |\n--------------------------------------\n> SITUAÇÃO: VARREDURA NOTURNA\n  CONCLUÍDA\n======================================\n> RESULTADOS\n- 01 ACAMPAMENTO DESMOBILIZADO\n- 03 ELEMENTOS DETIDOS (IDADE ESTIMADA\n  20–30 ANOS)\n- MATERIAL APREENDIDO: RÁDIO DE ONDAS\n  CURTAS, PANFLETOS, GARRAFAS DE VODKA\n======================================\n> BAIXAS\n- SEM BAIXAS PRÓPRIAS\n- 01 ELEMENTO HOSTIL ALVEJADO AO\n  TENTAR FUGA\n======================================\n> AVALIAÇÃO\n- OPERAÇÃO EXECUTADA COM ÊXITO\n- INDÍCIOS DE LIGAÇÃO COM CÉLULAS\n  INTERIOR DE SP\n- CÉLULA AINDA EM ATIVIDADE\n--------------------------------------\nFIM DO RELATÓRIO\n--------------------------------------\n2.1. Parâmetro [ID] ou [V]oltar:\n";
			writeText (output,texto)
        }
		else 
		if (logg.toUpperCase() == "478") {
			texto = "--------------------------------------\n|  REL. OPERAÇÃO FALCÃO VERMELHO     |\n--------------------------------------\n> SITUAÇÃO: INTERCEPTAÇÃO REALIZADA EM\n  ARMAZÉM 4-B, TERMINAL PORTUÁRIO\n======================================\n> RESULTADOS\n- 12 CAIXAS APREENDIDAS COM\n  EQUIPAMENTOS ELETRÔNICOS E MATERIAL\n  ESTRANGEIRO\n- 02 ELEMENTOS ESTRANGEIROS DETIDOS\n  (NACIONALIDADE: INDEFINIDA)\n======================================\n> BAIXAS\n- 01 AGENTE LEVEMENTE FERIDO\n   (ESCORIAÇÃO BRAÇO ESQ.)\n======================================\n> AVALIAÇÃO\n- OPERAÇÃO CONSIDERADA EXITOSA\n- PRESUNÇÃO DE TRÁFICO DE TECNOLOGIA\n======================================\n> OBS\nREQUER ANÁLISE DO MATERIAL ELETRÔNICO\nPELO SETOR TECNOLÓGICO (SCT/DOMUS)\n--------------------------------------\nFIM DO RELATÓRIO\n--------------------------------------\n2.1. Parâmetro [ID] ou [V]oltar:\n";
			writeText (output,texto)
        }
		else { 
		    writeText(output,">> PROCURANDO.......\n>> ERRO 404: NENHUM REGISTRO \n             COMPATÍVEL ENCONTRADO.\n>> VERIFIQUE OS DADOS INSERIDOS E\n             TENTE NOVAMENTE.\n--------------------------------------\n2.1. Parâmetro [ID] ou [V]oltar:\n")
		    playSound("ERROR");
		}
   }

function mostrarMenuPrincipal(){
	return ("--------------------------------------\n##       SISTEMA DOMUS - V2.4       ##\n##   CLASSIFICAÇÃO: CONFIDENCIAL    ##\n--------------------------------------\n1 - CONSULTA DE PESSOAS\n2 - CONSULTA DE OPERAÇÕES\n3 - INQUÉRITOS\n4 - ANÁLISES TÉCNICAS\n5 - ALERTAS E COMUNICADOS\n6 - CONFIGURAÇÕES DO SISTEMA\nR - REPETIR MENU\nF - FINALIZAR SESSÃO\n--------------------------------------\n")
}

function mostrarAnalisesTecnicas(){
	return ("--------------------------------------\n##   4. CONSULTA DE ANÁLISES        ##\n1 - POR IDENTIFICACAO\nR - REPETIR MENU\nV - VOLTAR\n--------------------------------------\n")	
}


function mostrarATPorID(){
	return("--------------------------------------\n4.1. Parâmetro [ID] ou [V]oltar:\n")	
}

function mostrarATImpressoes (){
	return("--------------------------------------\n4.2. Parâmetro [HASH] ou [V]oltar:\n")	
}

function mostrarConsultaPessoas(){
	return ("--------------------------------------\n##   1. CONSULTA DE PESSOAS         ##\n1 - POR NOME\n2 - POR IDENTIFICACAO\nR - REPETIR MENU\nV - VOLTAR\n--------------------------------------\n")
}

function mostrarOperacoes(){
	return ( decodeURIComponent(escape(atob("LS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0KIyMgICAyLiBDT05TVUxUQSBERSBPUEVSQcOHw5VFUyAgICAgICAjIwotLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLQpJRCAgQ09ELk5PTUUgICAgICBMT0NBTCAgICAgICAgICAgU1RBVAotLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLQoyMTkgU0VOVElORUxBICAgICBTUCBDQVBJVEFMICAgICAgIEFUVgoyMjMgQUxBUk1FIFZFUkRFICBTUCBJTlRFUklPUiAgICAgIElOQQozNDEgQVJFSUEgTkVHUkEgICBSSiBJTlRFUklPUiAgICAgIE9CUwo0NzggRkFMQ8ODTyBWRVJNLiAgUlMgUE9SVE8gQUxFICAgICBJTlQKNTkyIENPUlJFRE9SICAgICAgQU0gTUFOQVVTICAgICAgICBJTkEKNjAxIE1BTlRPIE5FR1JPICAgU0MgSU5URVJJT1IgICAgICBPQlMKLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0KQVRWfEFUSVZBICBJTkF8SU5BVElWQSAgT0JTfE9CU0VSVkHDh8ODTwpJTlR8SU5URVJWRU7Dh8ODTyAgTU9OfE1PTklUT1JBTUVOVE8gICAgCi0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tCjIuMS4gUGFyw6JtLiBbSURdIG91IFtWXW9sdGFyOgo="))))
}

function mostrarProjetos(){
	return ( decodeURIComponent(escape(atob("LS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0KIyMgICBYLiBDT05TVUxUQSBERSBQUk9KRVRPUyAgICAgICAgIyMKLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0KSUQgIENPRC5OT01FICAgICAgTE9DQUwgICAgICAgICAgIFNUQVQKLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0KNjY2IEFSTUFHRURPTSAgICAgUk4gSU5URVJJT1IgICAgICBJTkEKMDAxIENPTEhFSVRBICAgICAgRVggLSAgICAgICAgICAgICBBVFYKMDQyIFNBRlJBICAgICAgICAgQlIgLSAgICAgICAgICAgICAtLS0KMDU1IFMtNDcgT1JJT04gICAgTsODTyBMSVNUQURPICAgICAgLS0tCjA2MyBTLTQ5IExZUkEgICAgIE7Dg08gTElTVEFETyAgICAgIC0tLQowNjUgUy01MCBMWVJBICAgICBOw4NPIExJU1RBRE8gICAgICAtLS0KMDczIFMtNTIgQVFVSUxBICAgTsODTyBMSVNUQURPICAgICAgLS0tCjA3NyBTLTU0IERSQUNPICAgIE7Dg08gTElTVEFETyAgICAgIC0tLQowOTkgLS0tLS0tLS0tLS0gICAtLS0tLS0tLS0tLSAgICAgIC0tLQotLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLQpBVFZ8QVRJVkEgIElOQXxJTkFUSVZBICBPQlN8T0JTRVJWQcOHw4NPCklOVHxJTlRFUlZFTsOHw4NPICBNT058TU9OSVRPUkFNRU5UTyAgICAKLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0KWC4xLiBQYXLDom0uIFtJRF0gb3UgW1Zdb2x0YXI6Cg=="))))
}

function mostrarInqueritos(){
	return ("--------------------------------------\n##   3. CONSULTA DE INQUÉRITOS      ##\n--------------------------------------\n3.1. Parâmetro [ID] ou [V]oltar:\n")
}

function mostrarConsultaPessoasPorNome(){
	return("--------------------------------------\n1.1. Parâmetro [Nome] ou [V]oltar:\n")
}

function mostrarConsultaID(){
	return("--------------------------------------\n1.2. Parâmetro [ID] ou [V]oltar:\n")
}

function mostrarAlertas(){
	return("--------------------------------------\n5.1. Parâm. [dd/mm/aaaa] ou [V]oltar:\n")
}

// Mostrar Interface Principal 
const wait = (ms = 0) => new Promise(resolve => setTimeout(resolve, ms))
// Controle da Interface 
var boot = true;
var login = false;
var senha = false; 
var consulta = false;
var consultaID = false;
var consultaInqueritos = false;
var consultaAT = false; 
var consultaATImpressoes = false;
var consultaATID = false;
var consultAlertas = false;
var consultaOperacoes = false;
var consultaProjetos = false;
var user = 0;
var hierarquiaMenu = 1;

// Write text to a target element with a specified delay in ms
async function writeText(target, content, delay = 0) {
  // Loop through array of content characters
  return new Promise((resolve) => {
    // Make an array of the specified content
    const contentArray = content.split('')

    // Keep track of the character currently being written
    let current = 0
    while (current < contentArray.length) {
      ;((curr) => {
		setTimeout(() => {
          target.innerHTML += contentArray[curr]
          // Scroll to the bottom of the screen unless scroll is false
          window.scrollTo(0, document.body.scrollHeight)
          
          // Resolve the promise once the last character is written
          if (curr === contentArray.length - 1) resolve()
        }, delay * curr) // increase delay with each iteration
      })(current++)
    }
  })
}


// Executar um Comando. 
function execute(command) {
  if ( hierarquiaMenu == 1 ) {	
	switch(command.toLowerCase()) {
      case '':
        return `\n`

      case 'r':
        output.innerHTML = ''
        return mostrarMenuPrincipal()

      case 'f':
		login = true;
		senha = false; 
		user = 0;
		hierarquiaMenu = 1;
	    output.innerHTML = ''
		return 'Usuário desconectado.\n--------------------------------------\nLogin:'
      
	  case '1':
	    hierarquiaMenu = 2;
	    return mostrarConsultaPessoas()
		
	  case '2':
	    if (( user == 5 ) || ( user == 3 )) {
			playSound("WARNING");
			return ">> ERRO 011: NÍVEL DE ACESSO\n             INSUFICIENTE.\n"
		    }
		else 
			hierarquiaMenu = 10
		    consultaOperacoes = true 
		    return mostrarOperacoes()

      case '3':
        hierarquiaMenu = 5;
		consultaInqueritos = true
        return mostrarInqueritos()
		
	  case '4':
		hierarquiaMenu = 6;
		consultaAT = true;
		return mostrarAnalisesTecnicas()
		
	  case '5':
		hierarquiaMenu = 9;
		consultAlertas = true;
		return mostrarAlertas()

	  case '6':
	    if (( user == 5 ) || ( user == 3 ) || ( user == 1 )) {
			playSound("WARNING");
			return ">> ERRO 006: TERMINAL SEM AUTORIZAÇÃO\n             PARA ESTA FUNÇÃO.\n"
			}

      case 'x': 
	    if (( user == 5 ) || ( user == 3 )) {
			login = true;
			senha = false; 
			user = 0;
			hierarquiaMenu = 1;
			output.innerHTML = '';
			playSound("WARNING");
			return ">> ERRO 000: ERRO CRÍTICO.   TODAS AS\n        OPERAÇÕES FORAM INTERROMPIDAS.\nUsuário desconectado.\n--------------------------------------\nLogin:"
		}
		else 
			hierarquiaMenu = 99
		    consultaProjetos = true 
		    return mostrarProjetos()
	  
      default:
	    playSound("ERROR");
        return '>> ERRO 002: COMANDO DESCONHECIDO.\n             CONSULTE O MANUAL.\n'
      }
  }
  
  if ( hierarquiaMenu == 2 ) {	
	switch(command.toLowerCase()) {
      case '':
        return `\n`

      case 'r':
        output.innerHTML = ''
        return mostrarConsultaPessoas()

      case 'v':
		hierarquiaMenu = 1
	    output.innerHTML = ''
		return mostrarMenuPrincipal()
     
	  case '1':
	    hierarquiaMenu = 3
		consulta = true
	    return mostrarConsultaPessoasPorNome()
		
	  case '2':
	    hierarquiaMenu = 4
		consultaID = true
	    return mostrarConsultaID()
		
      default:
	    playSound("ERROR");
        return '>> ERRO 002: COMANDO DESCONHECIDO.\n             CONSULTE O MANUAL.\n'
      }
  }  

  // Consulta Pessoas por Nome 
  if ( hierarquiaMenu == 3 ) {	
	switch(command.toLowerCase()) {
      case '':
        return `\n`

      case 'r':
        output.innerHTML = ''
        return mostrarConsultaPessoasPorNome()

	  case 'v':
	    consulta = false 
	    output.innerHTML = ''
		hierarquiaMenu = 2
		return mostrarConsultaPessoas()

      default:
	    processConsultaPessoa(command.toLowerCase())
      }
  }

  // Consulta Pessoas por Identificação
  if ( hierarquiaMenu == 4 ) {	
	switch(command.toLowerCase()) {
      case '':
        return `\n`

	  case 'v':
	    consultaID = false 
	    output.innerHTML = ''
		hierarquiaMenu = 2
		return mostrarConsultaPessoas()

      case 'r':
        output.innerHTML = ''
        return mostrarConsultaID()

      default:
	    processConsultaID(command.toLowerCase())
      }
  }  

  // Consulta Inquéritos
  if ( hierarquiaMenu == 5 ) {	
	switch(command.toLowerCase()) {
      case '':
        return `\n`

      case 'r':
        output.innerHTML = ''
        return mostrarInqueritos()
      
	  case 'v':
	    output.innerHTML = ''
		hierarquiaMenu = 1
		consultaInqueritos = false
		return mostrarMenuPrincipal()

      default:
	    processInqueritos(command.toLowerCase())
      }
  }  
  
  // Consulta Análises Técnicas
  if ( hierarquiaMenu == 6 ) {	
	switch(command.toLowerCase()) {
      case '':
        return `\n`

      case 'r':
        output.innerHTML = ''
        return mostrarAnalisesTecnicas()

      case 'v':
		hierarquiaMenu = 1
	    output.innerHTML = ''
		return mostrarMenuPrincipal()
     
	  case '1':
	    hierarquiaMenu = 7
		consultaATID = true
	    return mostrarATPorID()
		
	  /*case '2':
	    hierarquiaMenu = 8
		consultaATImpressoes = true
	    return mostrarATImpressoes()*/

      default:
	    playSound("ERROR");
        return '>> ERRO 002: COMANDO DESCONHECIDO.\n             CONSULTE O MANUAL.\n'
      }
  }  
  
 
  // Consulta Análises Técnicas por ID
  if ( hierarquiaMenu == 7 ) {	
	switch(command.toLowerCase()) {
      case '':
        return `\n`

	  case 'v':
	    consultaATID = false 
	    output.innerHTML = ''
		hierarquiaMenu = 6
		return mostrarAnalisesTecnicas()

      case 'r':
        output.innerHTML = ''
        return mostrarATPorID()

      default:
	    processATPorID(command.toLowerCase())
      }
  }  
  
    // Consulta Análises Técnicas Impressões Digitais
  if ( hierarquiaMenu == 8 ) {	
	switch(command.toLowerCase()) {
      case '':
        return `\n`

	  case 'v':
	    consultaATID = false 
	    output.innerHTML = ''
		hierarquiaMenu = 6
		return mostrarAnalisesTecnicas()

      case 'r':
        output.innerHTML = ''
        return mostrarATImpressoes()

      defa22ult:
	    processATImpressoes(command.toLowerCase())
      }
  }
  
  // Consulta Alertas por Data
  if ( hierarquiaMenu == 9 ) {	
	switch(command.toLowerCase()) {
      case '':
        return `\n`

      case 'r':
        output.innerHTML = ''
        return mostrarAlertas()
      
	  case 'v':
	    output.innerHTML = ''
		hierarquiaMenu = 1
		consultAlertas = false
		return mostrarMenuPrincipal()

      default:
	    processAlertas(command.toLowerCase())
      }
  }
  
  // Consulta Operações
  if ( hierarquiaMenu == 10 ) {	
	switch(command.toLowerCase()) {
      case '':
        return `\n`

      case 'r':
        output.innerHTML = ''
        return mostrarOperacoes()
      
	  case 'v':
	    output.innerHTML = ''
		hierarquiaMenu = 1
		consultaOperacoes = false
		return mostrarMenuPrincipal()

      default:
	    processOperacoes(command.toLowerCase())
      }
  }
  
  // Consulta Projetos
  if ( hierarquiaMenu == 99 ) {	
	switch(command.toLowerCase()) {
      case '':
        return `\n`

      case 'r':
        output.innerHTML = ''
        return mostrarOperacoes()
      
	  case 'v':
	    output.innerHTML = ''
		hierarquiaMenu = 1
		consultaProjetos = false
		return mostrarMenuPrincipal()

      default:
	    processProjetos(command.toLowerCase())
      }
  }
}

// Variáveis
const instructions = document.getElementById('instructions')
const promptDiv = document.getElementById('prompt');
const cursor = document.getElementById('cursor');
const prompt = document.getElementById('prompt')
const commandInput = document.getElementById('command-input');
const hiddenInput = document.getElementById('hidden-input');
const output = document.getElementById('output')

// Execute page loading asynchronously once content has loaded
document.addEventListener('DOMContentLoaded', async () => {
  

  await writeText(output, "Press any key to boot...")
  prompt.prepend('>')
  cursor.innerHTML = '_'
})

  function focusInput() {
    hiddenInput.focus();
}

async function processaBoot(){
  login = true;
  boot = false;
  output.innerHTML = "";
  playSound("COMPUTER");
  await writeText(asciiText1, asciiArt1,4)
  await wait(500)
  await writeText(asciiText2, asciiArt2,1)
  await wait(500)
  await writeText(asciiText3, asciiArt3,8)
  await wait(500)
  await writeText(output, "Login:")
}

const asciiText1 = document.getElementById('asciiText1')
const asciiArt1 = asciiText1.innerText
asciiText1.innerHTML = ''

const asciiText2 = document.getElementById('asciiText2')
const asciiArt2 = asciiText2.innerText
asciiText2.innerHTML = ''

const asciiText3 = document.getElementById('asciiText3')
const asciiArt3 = asciiText3.innerText
asciiText3.innerHTML = ''


// Focar ao carregar
window.onload = focusInput;

// Focar quando clicar no prompt
promptDiv.addEventListener('click', focusInput);

// Manter foco sempre
hiddenInput.addEventListener('blur', focusInput);

// Atualiza texto digitado
hiddenInput.addEventListener('input', (e) => {
    commandInput.textContent = e.target.value;
});

// Trata teclas especiais
hiddenInput.addEventListener('keydown', (e) => {
    playSound('KEY');
	if ( boot == true ) {
   		 processaBoot();
		 e.key = null;
		 return;
	     }
	if (e.key === 'Backspace') {
        e.preventDefault();
        const atual = commandInput.textContent;
        commandInput.textContent = atual.slice(0, -1);
        hiddenInput.value = commandInput.textContent;
    }
    if (e.key === 'Enter') {
		  const command = commandInput.innerText
          hiddenInput.value = ''
		  commandInput.innerHTML = ''
 		  // reprint the entered command
 		  output.innerHTML += '<strong>' + command + '</strong><br>'	     
		  if ( login == true ) {
		    if ( senha == false ) 
		         processLogin(command)
		    else processSenha(command)
	        }
	      else
          if ( consulta == true ) {
		       processConsultaPessoa(command)
			   }
	      else
          if ( consultaID == true ) {
		       processConsultaID(command)
			   }
	      else
	      if ( consultaInqueritos == true ) {
		       processInqueritos(command)
	           }
		  else 
		  if ( consultaATImpressoes == true ) {
			   processATImpressoes(command)
			   }
		  else 
		  if ( consultaATID == true ) {
			   processATPorID(command)
			   }
		  else 
		  if ( consultAlertas == true ) {
			   processAlertas(command)
			   }
		  else 
		  if ( consultaOperacoes == true ) {
			   processOperacoes(command)
			   }
		  else 
		  if ( consultaProjetos == true ) {
			   processProjetos(command)
			   }
	      else 
		      writeText(output, execute(command))
    }

});
const texto2 = "--------------------------------------\nCOMUNICADO INTERNO - PRIORID. 3\n--------------------------------------\n> REFERÊNCIA: OCORRÊNCIA POLICIAL\n  PROXIMIDADES DE INSTALAÇÃO MILITAR\n> DATA: 11/11/1967\n> LOCAL: PRAIA DO CASSINO\n         RIO GRANDE - RS\n======================================\n> SUMÁRIO\n- REGISTRADO UM HOMICÍDIO NAS\n  IMEDIAÇÕES DO CENTRO DE TREINAMENTOS\n  DO 7º GRUPO DE ARTILHARIA DE COSTA\n  MOTORIZADO.\n- O CORPO DE UM INDIVÍDUO MASCULINO,\n  ADULTO, NÃO IDENTIFICADO ATÉ O\n  PRESENTE MOMENTO, FOI ENCONTRADO COM\n  EVIDENTES SINAIS DE EXECUÇÃO COM\n  O USO DE UM OBJETO PERFURANTE NAS\n  COSTAS.\n- OCORRÊNCIA DETECTADA POR TRANSEUNTES\n======================================\n> PROVIDÊNCIAS IMEDIATAS\n- ÁREA ISOLADA POLÍCIA DO EXÉRCITO\n- ACIONAMENTO DA POLÍCIA CIVIL\n- INVESTIGAÇÃO EM CURSO\n======================================\n> ORIENTAÇÃO:\n- MANTER SIGILO ABSOLUTO SOBRE O\n  OCORRIDO ATÉ SEGUNDA DETERMINAÇÃO.\n- AGUARDAR INSTRUÇÕES DA SEÇÃO DE\n  INTELIGÊNCIA REGIONAL (SIR/8ª RM).\n--------------------------------------\nFIM DO RELATÓRIO\n --------------------------------------\n6.1. Parâm. [dd/mm/aaaa] ou [V]oltar:\n\n";

const codificado = btoa(unescape(encodeURIComponent(texto2))); // Codifica em base64
//console.log("Base64:", codificado);
